if: tag IS blank

language: ruby
  
matrix:
  include:
    - name: "macOS Build"
      os: osx
      
    - name: "Linux Build"
      os: linux

script: date > file-$TRAVIS_OS_NAME.txt

before_deploy:
  - export TRAVIS_TAG="preview"

deploy:
  provider: releases
  api_key: $OAUTH_TOKEN
  skip_cleanup: true
  draft: true
  overwrite: true
  file_glob: true
  file: file-*.txt
