matrix:
  include:
    - name: "macOS"
      os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - name: "Windows + Linux"
      os: linux
      services: docker
      language: generic

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "yarn --link-duplicates --pure-lockfile && yarn dist --linux --win"
    else
      yarn dist
    fi
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  except:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

deploy:
  provider: releases
  api_key: $OAUTH_TOKEN
  file_glob: true
  file:
    - dist/read-it-aloud*.exe
    - dist/read-it-aloud**.exe
    - dist/read-it-aloud/*.exe
    - dist/read-it-aloud/**.exe
    - dist/**/*.zip
    - dist/**/*.dmg
    - dist/**/*.deb
    - dist/**/*.snap
    - dist/**/*.AppImage
    - dist/**/*.tar.gz
  skip_cleanup: true
  draft: true
  on:
    all_branches: true
