language: ruby
sudo: false
dist: trusty

language: ruby

install: skip
script: date > file-$TRAVIS_OS_NAME.txt

jobs:
  include:
    - stage: compile macos assets
      os: osx
      deploy:
        provider: releases
        api_key: $OAUTH_TOKEN
        draft: true
        skip_cleanup: true
        file: file-$TRAVIS_OS_NAME.txt
        on:
          all_branches: true
    - stage: compile linux assets and publish
      deploy:
        provider: releases
        api_key: $OAUTH_TOKEN
        draft: true
        skip_cleanup: true
        file: file-$TRAVIS_OS_NAME.txt
        on:
          all_branches: true
